name: Projects API

on:
  # schedule:
    # # At 18:30 UTC on everyday (12.00 mid night in Sri Lanka)
    # - cron: "30 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Python script
        run: |
          cd ./python_scripts
          python3 projects.py

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Projects API was updated by GitHub Actions" || echo "No changes to commit on Projects API"
          git push
